group:
  - files:
    - source: public/
      dest: public/
      deleteOrphaned: true
    - source: src/
      dest: src/
      deleteOrphaned: true
    - source: .eslintrc.json
      dest: .eslintrc.json
    - source: i18n.config.json
      dest: i18n.config.json
    - source: next.config.mjs
      dest: next.config.mjs
    - source: package-lock.json
      dest: package-lock.json
    - source: package.json
      dest: package.json
    - source: postcss.config.mjs
      dest: postcss.config.mjs
    - source: tailwind.config.ts
      dest: tailwind.config.ts
    - source: tsconfig.json
      dest: tsconfig.json
    repos: |
      SkyHearts/preview-eth-globe